server:
  port: 9090

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: study.thboard2.domain.vo
  configuration:
    jdbc-type-for-null: null

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(LOAD_BALANCE=ON)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ORCL)))
    hikari:
      username: DEV_01
      password: 1234
      connection-timeout: 60000
      auto-commit: false
  thymeleaf:
    cache: false


